#!/bin/bash
opts=(
    --verbosity:0
    --hints:off
    #--forceBuild:on
    --opt:speed

    # the following don't seem to affect performance much 1.17s vs 1.33s
    #--assertions:off
    #--checks:off

)

shellquotex nim "${opts[@]}" c cribbage.nim || exit

hands=(
    7C-9H-5H-5C-5D-JS
    2H-2C-2D-9S-QH-QC
    3H-3C-8D-7S-5H-2C
)

exit=0

shellquotex time ./cribbage "${hands[@]}" || exit=1
shellquotex time ~/site/bin/cribbage "${hands[@]}" || exit=1

exit $exit
